# GLOBAL CONFIGURATION
timezone: Asia/Ho_Chi_Minh

# COLLECTIONS CONFIGURATION
collections_config:
  projects:
    path: src/content/projects
    name: Projects
    icon: business
    # Tell CloudCannon strictly to look for Markdown files
    glob: "**/*.md"
    # When creating a new file, use this extension
    new_file_extension: "md"
    # Define the inputs so it doesn't "guess" and fail
    _inputs:
      title:
        type: text
        label: Project Title
      description:
        type: textarea
        label: Short Description
      image:
        type: image
        label: Main Cover Image
      tags:
        type: list
        label: Tags (Categories)
      gallery:
        type: array
        label: Image Gallery
        options:
          image: true

  products:
    path: src/content/products
    name: Products
    icon: shopping_cart
    glob: "**/*.md"
    new_file_extension: "md"
    _inputs:
      title:
        type: text
      image:
        type: image
      gallery:
        type: array
        options:
          image: true

# PATHS
paths:
  uploads: public/uploads

# EDITOR SETTINGS
_editor:
  default_path: /