<<<<<<< HEAD
# GLOBAL
timezone: Asia/Ho_Chi_Minh

# INPUT CONFIGURATION (How the fields look)
_inputs:
  date:
    instance_value: NOW
  gallery:
    type: array
    options:
      image: true
  tags:
    type: list
  image:
    type: image
  description:
    type: textarea

# COLLECTIONS
=======
paths:
  uploads: public/uploads
>>>>>>> 030df18dc8e6a661e8615d3cb00a006f983be7cf
collections_config:
  projects:
    path: src/content/projects
    name: Projects
<<<<<<< HEAD
    icon: business
    glob: "**/*.md"
    # FILTER: Hide the schema file from the list so you don't edit it by mistake
    filter:
      exclude:
        - "_schema.md"
    # SCHEMA: This tells the "Add" button to copy your blueprint
    schemas:
      default:
        path: src/content/projects/_schema.md
        name: New Project

  products:
    path: src/content/products
    name: Products
    icon: shopping_cart
    glob: "**/*.md"
    filter:
      exclude:
        - "_schema.md"
    schemas:
      default:
        path: src/content/products/_schema.md
        name: New Product

# PATHS
paths:
  uploads: public/uploads
=======
    icon: add_business
    disable_url: false
    _inputs:
      gallery:
        type: array
        options: {}
        cascade: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  products:
    path: src/content/products
    name: Products
    icon: domain_add
    disable_url: false
    _inputs:
      gallery:
        type: array
        options: {}
        cascade: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  date:
    instance_value: NOW
    cascade: true
timezone: Etc/UTC
>>>>>>> 030df18dc8e6a661e8615d3cb00a006f983be7cf
