paths:
  uploads: public/uploads
collections_config:
  projects:
    path: src/content/projects
    name: Projects
    icon: add_business
    disable_url: false
    _inputs:
      gallery:
        type: array
        options: {}
        cascade: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  products:
    path: src/content/products
    name: Products
    icon: domain_add
    disable_url: false
    _inputs:
      gallery:
        type: array
        options: {}
        cascade: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  date:
    instance_value: NOW
    cascade: true
timezone: Etc/UTC
